apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

# ğŸ”¥ ì´ë¯¸ì§€ ì¹˜í™˜: base ì—ì„œëŠ” ë‹¨ìˆœ ì´ë¦„(saleor-core ë“±)ì„ ì“°ê³ 
# dev overlay ì—ì„œë§Œ ECR ê²½ë¡œë¡œ ë³€ê²½
images:
  - name: saleor-core
    newName: 069423016509.dkr.ecr.ap-northeast-3.amazonaws.com/saleor-3tier-dev-core
    newTag: latest
  - name: saleor-storefront
    newName: 069423016509.dkr.ecr.ap-northeast-3.amazonaws.com/saleor-3tier-dev-storefront
    newTag: latest
  - name: saleor-dashboard
    newName: 069423016509.dkr.ecr.ap-northeast-3.amazonaws.com/saleor-3tier-dev-dashboard
    newTag: latest
