apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saleor-core-api-ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # frontend Ingress와 같은 ALB 사용
    alb.ingress.kubernetes.io/group.name: saleor-dev
    alb.ingress.kubernetes.io/group.order: "2"

    # 헬스체크 (Core는 /health/ 쓰는게 깔끔)
    alb.ingress.kubernetes.io/healthcheck-path: /health/
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"

    # HTTPS 붙일 때 동일하게 여기에도 certificate / ssl-redirect 추가
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-3:ACCOUNT_ID:certificate/XXXX
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
    - host: u3-api.msp-g1.click
      http:
        paths:
          - path: /graphql/
            pathType: Prefix
            backend:
              service:
                name: saleor-core
                port:
                  number: 8000
