apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - saleor-core/deployment.yaml
  - saleor-core/service.yaml
  - saleor-storefront/deployment.yaml
  - saleor-storefront/service.yaml
  - saleor-dashboard/deployment.yaml
  - saleor-dashboard/service.yaml
  - ingress/ingress.yaml
