apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-storefront
  namespace: frontend
  labels:
    app: saleor-storefront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saleor-storefront
  template:
    metadata:
      labels:
        app: saleor-storefront
    spec:
      containers:
        - name: saleor-storefront
          image: 069423016509.dkr.ecr.ap-northeast-3.amazonaws.com/saleor-3tier-dev-storefront:latest
          ports:
            - containerPort: 3000
          env:
            # 서버에서 Core 접근용
            - name: API_URL
              value: "http://saleor-core.backend.svc.cluster.local:8000/graphql/"

            # Next.js (서버/클라이언트 공통)에서 쓰는 GraphQL 엔드포인트
            - name: NEXT_PUBLIC_SALEOR_API_URL
              value: "http://saleor-core.backend.svc.cluster.local:8000/graphql/"

            # 이 스토어의 외부 URL (메타태그, 링크용)
            - name: NEXT_PUBLIC_STOREFRONT_URL
              value: "http://u3-store.msp-g1.click"

            # 채널 이름 (기본값이 default-channel 이라면)
            - name: NEXT_PUBLIC_SALEOR_CHANNEL
              value: "default-channel"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10   # 컨테이너 뜨고 10초 뒤부터 체크 시작
            periodSeconds: 10         # 10초마다 체크
            timeoutSeconds: 5
            failureThreshold: 3       # 3번 실패하면 NotReady 처리
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # 부팅하고 안정화 시간
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5       # 5번 연속 실패하면 컨테이너 재시작

